// Generated by https://quicktype.io

export interface IGetItems {
    author:     Author;
    categories: string[];
    items:      Item[];
}

export interface Author {
    name:     string;
    lastname: string;
}

export interface Item {
    id:           string;
    title:        string;
    price:        Price;
    picture:      string;
    condition:    string;
    free_shiping: boolean;
    seller_address: string;
}

export interface Price {
    currency: string;
    amount:   number | string;
    decimals: number | string;
}